before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y libzmq-dev
script: bundle exec rspec
language: ruby
rvm:
  - 2.4.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
